server:
  port: 80
spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.46.180:3306/findlover?useSSL=false
#      url: jdbc:mysql://localhost/findlover?useSSL=false
      username: root
      password: gss991
#      password: root
      initial-size: 1
      min-idle: 1
      max-idle: 2
      max-total: 2
      max-wait-millis: 6000
  mail:
    host: smtp.qq.com
    port: 465
    username: 383196019@qq.com
    password: djjfuajqwdvbbghb
    properties:
      mail:
        smtp:
          auth: true
          timeout: 30000
          connectiontimeout: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 25MB


# Mybatis config
mybatis:
  type-aliases-package: com.hpe.findlover.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true


pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql

mapper:
  mappers:
    - com.hpe.util.BaseTkMapper
  not-empty: false
  identity: MYSQL

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList: 192.168.111.130:22122  #tracker路径，TrackerList参数,支持多个