server:
  port: 80

spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.46.180:3306/findlover?useSSL=false
      username: root
      password: gss991
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-total: 20
      max-wait-millis: 6000

# Mybatis config
mybatis:
  type-aliases-package: com.hpe.findlover.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mapper:
    mappers:
        - com.hpe.util.BaseTkMapper
    not-empty: false
    identity: MYSQL

